import Link from 'next/link'
import "./styles/styles.css"
import Nav from './components/Nav'


export const metadata = {
  title: 'Face App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        {children}
      </body>
    </html>
  )
}
